services:
  Postgres:
    container_name: "Postgres"
    image: "docker.io/library/postgres:17.2"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "evMpFiQ8Al2vMNSVQOedG6"
    volumes:
    - "nihongobot-apphost-911f0b78b9-postgres-data:/var/lib/postgresql/data"
    ports:
    - target: 5432
      published: 5432
    restart: unless-stopped
  NihongoBotServer:
    container_name: "NihongoBotServer"
    image: "nihongobotserver:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__NihongoBotDB: "Host=Postgres;Port=5432;Username=postgres;Password=evMpFiQ8Al2vMNSVQOedG6;Database=NihongoBotDB"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  NihongoBot:
    container_name: "NihongoBot"
    image: "nihongobot:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__NihongoBotDB: "Host=Postgres;Port=5432;Username=postgres;Password=evMpFiQ8Al2vMNSVQOedG6;Database=NihongoBotDB"
    restart: unless-stopped
volumes:
  nihongobot-apphost-911f0b78b9-postgres-data: {}
